### ISSUE TITLE
Ripple remains visible

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/paper-ripple#16]
Just tested in current version e.g. demo.html

Press and hold mouse in first box until ripple fully shows, release mouse button without moving mouse. 

Result: the ripple remains visible.
Expected: ripple is removed when mouse is released

If the button is released before the circle is complete it disappears, same if the mouse is moved.

e.g. 
![2014-09-09_1533b](https://cloud.githubusercontent.com/assets/7462342/4207610/42b74284-3858-11e4-95fc-d3b3e17c040c.png)

**Comment by dheera** [comment]
This still occurs, even with 1.1.4, and even on Polymer's own official website.

![2015-10-07 05 47 12](https://cloud.githubusercontent.com/assets/1786477/10329953/fde4f482-6cb6-11e5-8cd2-1b7eb500e50c.png)
