### ISSUE TITLE
[0.8] The `noink` attribute has no effect

### ISSUE THREAD

**Issue by ssorallen** [Polymer/paper-ripple#33]
`this.host` in JS and `:host` in CSS refer to different elements, and so paper-ripple's use of the two leads to it not honoring the `noink` attribute.

**Comment by tekkamanendless** [comment]
I'm seeing this on the current 1.0.2, currently.  Putting "noink" on the "paper-ripple" itself (or its parent element) has no effect whatsoever.

**Comment by cdata** [comment]
I think this has been fixed. Please re-open if it has not been!
