### ISSUE TITLE
Why is paper-ripple being depreciated?

### ISSUE THREAD

**Issue by sharpmachine** [Polymer/paper-ripple#41]
More of a question rather than an issue, but just wondering what we are meant to use once we upgrade to polymer 0.9 is there's paper ripple?

**Comment by notwaldorf** [comment]
It's not being deprecated (i think the `readme` link is a typo which I'm about to fix). The 0.9 version is here: https://github.com/polymerelements/paper-ripple :)

**Comment by sharpmachine** [comment]
Cool.  Thanks!
